Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2018-11, with the labels that each got.

#1515 PrefixAllGlobals: verify that namespace names use a prefix
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.4.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Labels: Component: Extras, Status: Review Ready, Type: Enhancement

#1517 Compatibility-fix for PHPCS 3.4.0
  WordPress/Tests/PHP/TypeCastsUnitTest.inc
  WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed
  WordPress/Tests/PHP/TypeCastsUnitTest.php
  WordPress/Tests/PHP/YodaConditionsUnitTest.inc
  WordPress/Tests/PHP/YodaConditionsUnitTest.php
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Labels: Focus: Modern PHP, Status: Review Ready, Upstream: PHPCS

#1516 Sniff::is_class_property: bug fix
  WordPress/Sniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Labels: Status: Review Ready, Type: Bug

#1519 WordPress.PHP.TypeCasts: recognize casts independently of inside cast spacing
  WordPress/Sniffs/PHP/TypeCastsSniff.php
  WordPress/Tests/PHP/TypeCastsUnitTest.inc
  WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed
  WordPress/Tests/PHP/TypeCastsUnitTest.php
Labels: Component: Core, Status: Review Ready, Type: Bug

#1518 Fix duplicate error being thrown / space after cast
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc.fixed
  WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.php
Labels: Component: Core, Status: Review Ready

#1521 Sniff::has_whitelist_comment(): Minor bug fix
  WordPress/Sniff.php
Labels: Status: Review Ready, Type: Bug

#1522 CodeAnalysis/Emptystatement: bug fix
  WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc.fixed
Labels: Status: Review Ready, Type: Bug

#1458 Create issue templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/dependency-change.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Meta: Repo, Type: Enhancement

#1499 Docs: Remove and update VIP link references
  README.md
  WordPress-VIP/ruleset.xml
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/DB/SlowDBQuerySniff.php
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Sniffs/VIP/AdminBarRemovalSniff.php
  WordPress/Sniffs/VIP/CronIntervalSniff.php
  WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php
  WordPress/Sniffs/VIP/OrderByRandSniff.php
  WordPress/Sniffs/VIP/PluginMenuSlugSniff.php
  WordPress/Sniffs/VIP/PostsPerPageSniff.php
  WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPress/Sniffs/VIP/RestrictedVariablesSniff.php
  WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php
  WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
  WordPress/Sniffs/VIP/SlowDBQuerySniff.php
  WordPress/Sniffs/VIP/TimezoneChangeSniff.php
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Sniffs/WP/PostsPerPageSniff.php
  WordPress/Sniffs/WP/TimezoneChangeSniff.php
Labels: Status: Review Ready

#1530 Wording: Change text-domain to text domain
  CHANGELOG.md
  README.md
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Tests/WP/I18nUnitTest.1.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
Labels: Status: Review Ready

#1527 Change log for WPCS version 1.2.0
  CHANGELOG.md
Labels: Status: Review Ready, Type: Documentation

#1532 PrecisionAlignment: bug fix
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7a.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7b.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7c.inc
Labels: Status: Review Ready, Type: Bug

#1533 PrefixAllGlobals: improve error position precision
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Labels: Status: Review Ready, Type: Enhancement
