Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2018-08, with the labels that each got.

#1448 Fix links to the Core handbook
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Sniffs/Functions/FunctionCallSignatureNoParamsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
Labels: Status: Review Ready, Type: Chores

#1437 PrefixAllGlobals: add recording of metrics
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Status: Review Ready, Type: Enhancement

#1452 Move the WPCS `WordPress.CodeAnalysis.EmptyStatement` from `Extra` to `Core`
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
Labels: Status: Review Ready

#1453 Core ruleset: change behaviour for the `PEAR/FunctionCallSignature` sniff
  WordPress-Core/ruleset.xml
  WordPress/PHPCSAliases.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1450 New WPCS native `NoSilencedErrors` sniff
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1433 Composer: Make script DRY
  composer.json
Labels: Status: Review Ready, Type: Chores/Cleanup

#1456 Sniff::is_token_in_test_method(): allow for anonymous classes
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.3.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Labels: Focus: Modern PHP, Status: Review Ready, Type: Bug, Type: Enhancement

#1463 Move CommentedOutCode check from Docs to Extra
  WordPress-Docs/ruleset.xml
  WordPress-Extra/ruleset.xml
Labels: Component: Extras, Status: Review Ready, Type: Enhancement

#1469 Sniff::is_safe_casted(): minor efficiency fixes
  WordPress/Sniff.php
Labels: Status: Review Ready, Type: Enhancement
