Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2018-07, with the labels that each got.

#1405 PreparedSQL: make the sniff more code style independent
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Tests/DB/PreparedSQLUnitTest.inc
Labels: Status: Review Ready, Type: Bug

#1404 CronInterval: make the sniff more code style independent
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Tests/WP/CronIntervalUnitTest.inc
  WordPress/Tests/WP/CronIntervalUnitTest.php
Labels: Status: Review Ready, Type: Bug

#1374 AlternativeFunctions: improve handling of file_get_contents()
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Labels: Status: Review Ready

#1408 Various minor fixes
  Test/Standards/AbstractSniffUnitTest.php
  WordPress/Sniffs/Classes/ClassInstantiationSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Sniffs/WP/PostsPerPageSniff.php
Labels: Status: Review Ready, Type: Bug

#1407 PHPCS cross-version compatibility: account for the new PHPCS native whitelist comments
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc.fixed
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc.fixed
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/Files/FileNameUnitTests/PHPCSAnnotations/blanket-disable.inc
  WordPress/Tests/Files/FileNameUnitTests/PHPCSAnnotations/non-relevant-disable.inc
  WordPress/Tests/Files/FileNameUnitTests/PHPCSAnnotations/partial-file-disable.inc
  WordPress/Tests/Files/FileNameUnitTests/PHPCSAnnotations/rule-disable.inc
  WordPress/Tests/Files/FileNameUnitTests/PHPCSAnnotations/wordpress-disable.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/WP/I18nUnitTest.2.inc
  WordPress/Tests/WP/I18nUnitTest.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.2.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.2.inc.fixed
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.5.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.6.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Status: Review Ready, Type: Bug, Type: Enhancement

#1412 Travis: add builds to test against minimum supported PHPCS 3.x version
  .travis.yml
Labels: Status: Review Ready

#1411 Performance: use FQN for global constants
  Test/Standards/AbstractSniffUnitTest.php
  Test/Standards/AllSniffs.php
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/AbstractVariableRestrictionsSniff.php
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/Classes/ClassInstantiationSniff.php
  WordPress/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php
  WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Sniffs/DB/SlowDBQuerySniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/Functions/FunctionCallSignatureNoParamsSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/PHP/DiscourageGotoSniff.php
  WordPress/Sniffs/PHP/StrictComparisonsSniff.php
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/VIP/AdminBarRemovalSniff.php
  WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
  WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/DisallowInlineTabsSniff.php
  WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Status: Review Ready, Type: Chores

#1414 Performance: use FQN for functions which can use PHP7 compile time opcodes
  Test/Standards/AbstractSniffUnitTest.php
  Test/Standards/AllSniffs.php
  Test/phpcs3-bootstrap.php
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/AbstractVariableRestrictionsSniff.php
  WordPress/PHPCSAliases.php
  WordPress/PHPCSHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/SlowDBQuerySniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/VIP/AdminBarRemovalSniff.php
  WordPress/Sniffs/VIP/PostsPerPageSniff.php
  WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Labels: Status: Review Ready

#1415 Travis/PHPCS: check WPCS own code for PHP cross-version compatibility
  .phpcs.xml.dist
  .travis.yml
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  composer.json
Labels: Status: Review Ready, Type: Chores

#1366 Check for deprecated parameter values
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php
Labels: Component: Extras, Status: Review Ready, Type: Enhancement

#1378 Added Enqueued functions check for version and in footer
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Labels: Component: Extras, Status: Review Ready, Type: Enhancement

#1421 Fix false positive violation for return type colon
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
Labels: Status: Review Ready

#1410 Deprecate Remaining VIP sniffs
  README.md
  WordPress-VIP/ruleset.xml
  WordPress/AbstractVariableRestrictionsSniff.php
  WordPress/Sniff.php
  WordPress/Sniffs/VIP/AdminBarRemovalSniff.php
  WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php
  WordPress/Sniffs/VIP/OrderByRandSniff.php
  WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php
  WordPress/Sniffs/VIP/RestrictedVariablesSniff.php
  WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php
  WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
  WordPress/Sniffs/VIP/SuperGlobalInputUsageSniff.php
  WordPress/Tests/VIP/AdminBarRemovalUnitTest.php
  WordPress/Tests/VIP/FileSystemWritesDisallowUnitTest.inc
  WordPress/Tests/VIP/FileSystemWritesDisallowUnitTest.php
  WordPress/Tests/VIP/OrderByRandUnitTest.inc
  WordPress/Tests/VIP/OrderByRandUnitTest.php
  WordPress/Tests/VIP/RestrictedFunctionsUnitTest.inc
  WordPress/Tests/VIP/RestrictedFunctionsUnitTest.php
  WordPress/Tests/VIP/RestrictedVariablesUnitTest.inc
  WordPress/Tests/VIP/RestrictedVariablesUnitTest.php
  WordPress/Tests/VIP/SessionFunctionsUsageUnitTest.inc
  WordPress/Tests/VIP/SessionFunctionsUsageUnitTest.php
  WordPress/Tests/VIP/SessionVariableUsageUnitTest.php
  WordPress/Tests/VIP/SuperGlobalInputUsageUnitTest.php
  WordPress/ruleset.xml
Labels: Status: Awaiting Feedback, Status: Review Ready, Type: Cleanup

#1426 Composer & Readme: update organisation name PHPCompatibility
  README.md
  composer.json
Labels: Status: Review Ready, Type: Chores, Type: Documentation

#1428 Contributing: discourage adding new whitelist comments
  .github/CONTRIBUTING.md
Labels: Status: Review Ready, Type: Documentation

#1431 WordPress ruleset: fix deprecation notices coming through
  WordPress/ruleset.xml
Labels: Status: Review Ready, Type: Bug

#1430 Travis: add a new check for early detection of ruleset problems
  .phpcs.xml.dist
  .travis.yml
  bin/class-ruleset-test.php
Labels: Status: Review Ready, Type: Chores

#1434 Changelog: bring back `unreleased` section
  CHANGELOG.md
Labels: Status: Review Ready

#1435 Travis: cache composer downloads
  .travis.yml
Labels: Status: Review Ready, Type: Chores
