Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2018-09, with the labels that each got.

#1457 GlobalVariablesOverride: detect variable overrides in global namespace
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.2.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.3.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Labels: Status: Review Ready, Type: Bug, Type: Enhancement

#1464 PrecisionAlignment: prevent false positive for inline javascript comments
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Status: Review Ready, Type: Bug

#1468 Sniff::is_in_isset_or_empty(): improve code-style independence
  WordPress/Sniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Labels: Status: Review Ready, Type: Bug

#1478 .gitignore: remove IDE specific files/folders
  .gitignore
Labels: Status: Review Ready, Type: Chores/Cleanup

#1479 ValidatedSanitizedInput: bug fix different quote style array keys
  WordPress/Sniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Labels: Status: Review Ready, Type: Bug

#1470 Release version 1.1.0
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  WordPress-Core/ruleset.xml
  WordPress-Docs/ruleset.xml
  WordPress-Extra/ruleset.xml
  WordPress/PHPCSAliases.php
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Sniffs/Functions/FunctionCallSignatureNoParamsSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.3.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.2.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.3.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
  composer.json
Labels: Meta: Repo

#1483 Core: New sniff to examine type casts
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/PHP/TypeCastsSniff.php
  WordPress/Tests/PHP/TypeCastsUnitTest.inc
  WordPress/Tests/PHP/TypeCastsUnitTest.inc.fixed
  WordPress/Tests/PHP/TypeCastsUnitTest.php
Labels: Component: Core, Status: Review Ready, Type: Enhancement

#1482 Core ruleset: update inline documentation
  WordPress-Core/ruleset.xml
Labels: Component: Core, Status: Review Ready, Type: Chores/Cleanup, Type: Documentation

#1488 Composer: various tweaks
  composer.json
Labels: Status: Review Ready, Type: Enhancement

#1489 Composer: Normalize composer.json
  composer.json
Labels: Status: Review Ready, Type: Chores/Cleanup
