Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-02, with the labels that each got.

#1643 Travis: test builds against PHP 7.4 & work around for PHPUnit 8
  .travis.yml
Labels: Priority: High, Status: Review Ready, Type: Chores/Cleanup

#1644 WP.EnqueuedResources: bug fix
  WordPress/Sniffs/WP/EnqueuedResourcesSniff.php
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc
Labels: Status: Review Ready, Type: Bug

#1645 Remove `sudo: false`
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1649 AlternativeFunctions: allow for php://input used with file_get_contents()
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
Labels: Status: Review Ready, Type: Enhancement

#1647 PrefixAllGlobals: improve error message clarity
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Status: Review Ready, Type: Enhancement
