Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-09, with the labels that each got.

#1795 AlternativeFunctions: add extra unit test
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1799 YodaConditions: minor efficiency fix
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1729 New error handling Deprecated Classes and Functions
  WordPress/Docs/WP/DeprecatedClassesStandard.xml
  WordPress/Docs/WP/DeprecatedFunctionsStandard.xml
  WordPress/Docs/WP/DeprecatedParameterValuesStandard.xml
  WordPress/Docs/WP/DeprecatedParametersStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1800 DisallowShortTernary: improve docs
  WordPress/Docs/PHP/DisallowShortTernaryStandard.xml
Labels: Status: Review Ready, Type: Bug, Type: Documentation

#1801 Documentation Class Instantiation
  WordPress/Docs/Classes/ClassInstantiationStandard.xml
Labels: Type: Documentation
