Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-12, with the labels that each got.

#1840 Travis: don't allow PHP 7.4 build to fail
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1837 ControlStructureSpacing: fix undefined index error
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
Labels: Status: Review Ready, Type: Bug

#1842 CommaAfterArrayItem: add metrics for comma after last item
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
Labels: Status: Review Ready, Type: Enhancement

#1843 NoSilencedErrors: improve consistency metrics
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
Labels: Status: Review Ready, Type: Bug

#1844 Travis: test against PHP 7.4, not snapshot
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1848 Fix off-by-one error when $treat_files_as_scoped is true
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.6.inc
Labels: Focus: WP interoperability, Status: Awaiting Feedback, Type: Bug
