Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-11, with the labels that each got.

#1746 Fixes #1696, errors on invalid post type
  WordPress-Extra/ruleset.xml
  WordPress/Docs/NamingConventions/ValidPostTypeSlugStandard.xml
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
  WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.inc
  WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.php
Labels: Component: Extras, Focus: WP interoperability, Status: Review Ready, Type: Enhancement

#1829 Update default minimum supported WP version
  WordPress/Sniff.php
  WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
  WordPress/Tests/WP/DeprecatedClassesUnitTest.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1823 Adds documentation for WordPress.WP.CronInterval
  WordPress/Docs/WP/CronIntervalStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1732 Docs: Add PostsPerPage XML doc
  WordPress/Docs/WP/PostsPerPageStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1730 Adds Ini_set documentation
  WordPress/Docs/PHP/IniSetStandard.xml
Labels: Type: Documentation

#1831 Various minor documentation fixes
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
Labels: Status: Review Ready, Type: Documentation

#1824 Adds documentation for WordPress.WP.EnqueuedResources.
  WordPress/Docs/WP/EnqueuedResourcesStandard.xml
Labels: Type: Documentation

#1826 Adds WP.Security.SafeRedirect documentation.
  WordPress/Docs/Security/SafeRedirectStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1833 Changelog for WPCS 2.2.0
  CHANGELOG.md
Labels: Status: Review Ready, Type: Documentation
