Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-10, with the labels that each got.

#1804 CapitalPDangit: minor tweak
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
Labels: Status: Review Ready, Type: Enhancement

#1806 PrefixAllGlobals + ValidFunctionName: ignore deprecated methods by design
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
Labels: Component: Core, Component: Extras, Status: Review Ready, Type: Enhancement

#1809 DeprecatedClasses: update the sniff
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
  WordPress/Tests/WP/DeprecatedClassesUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1744 Docs/WordPress.Arrays.ArrayIndentation
  WordPress/Docs/Arrays/ArrayIndentationStandard.xml
Labels: Type: Documentation

#1737 Array sniffs documentation (Related to #1722)
  WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml
  WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml
Labels: Type: Documentation

#1810 DeprecatedFunctions: update function list
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup, Type: Enhancement

#1815 ValidHookName: minor efficiency tweaks
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1817 ValidHookName: add documentation
  WordPress/Docs/NamingConventions/ValidHookNameStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1818 EscapeOutput: allow for typical pattern with `_deprecated_file()`
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1820 ValidHookName: improve error messages
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1808 New DateTime.CurrentTimeTimestamp sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/DateTime/CurrentTimeTimestampStandard.xml
  WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc.fixed
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.php
Labels: Component: Core, Focus: DateTime, Status: Review Ready, Type: Enhancement

#1822 PrefixAllGlobals: minor efficiency tweak
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup
