Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-07, with the labels that each got.

#1755 Added remaining plugin load globals
  WordPress/Sniff.php
Labels: Focus: WP interoperability, Type: Enhancement

#1758 WordPress ruleset: efficiency fix
  WordPress/ruleset.xml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1738 Docs/WordPress.WhiteSpace.CastStructureSpacing
  WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml
Labels: Type: Documentation

#1725 Docs/WordPress.WhiteSpace.PrecisionAlignment
  WordPress/Docs/WhiteSpace/PrecisionAlignmentStandard.xml
Labels: Type: Documentation

#1735 Docs/WordPress.WhiteSpace.DisallowInlineTabs
  WordPress/Docs/WhiteSpace/DisallowInlineTabsStandard.xml
Labels: Type: Documentation

#1770 Core: Add upstream Generic.Arrays.DisallowShortArraySyntax sniff
  WordPress-Core/ruleset.xml
Labels: Component: Core, Status: Review Ready, Type: Enhancement

#1768 New DisallowShortTernary sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/PHP/DisallowShortTernaryStandard.xml
  WordPress/Sniffs/PHP/DisallowShortTernarySniff.php
  WordPress/Tests/PHP/DisallowShortTernaryUnitTest.inc
  WordPress/Tests/PHP/DisallowShortTernaryUnitTest.php
Labels: Component: Core, Focus: Modern PHP, Status: Review Ready, Type: Enhancement

#1776 EscapeOutput: improve the error message for non-escaped variables
  WordPress/Sniffs/Security/EscapeOutputSniff.php
Labels: Status: Review Ready, Type: Enhancement

#1773 GlobalVariablesOverride/PrefixAllGlobals: handle WP variables intended to be overwritten
  WordPress/Sniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
Labels: Component: Extras, Status: Review Ready, Type: Bug

#1772 PHP 7.4 compatibility / defensive coding
  WordPress/Sniff.php
Labels: Status: Review Ready, Type: Bug

#1777 New CodeAnalysis/EscapedNotTranslated sniff
  WordPress-Extra/ruleset.xml
  WordPress/Docs/CodeAnalysis/EscapedNotTranslatedStandard.xml
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.inc
  WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.php
Labels: Component: Extras, Focus: Code Analysis, Status: Review Ready, Type: Enhancement

#1767 CastStructureSpacing: allow for spread operator
  WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc
  WordPress/Tests/WhiteSpace/CastStructureSpacingUnitTest.inc.fixed
Labels: Status: Review Ready, Type: Enhancement

#1779 ArrayKeySpacingRestrictions: add space size check & fix errors in one go
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc.fixed
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.php
Labels: Status: Review Ready, Type: Bug, Type: Enhancement

#1780 Array sniffs: ignore short lists
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc.fixed
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.php
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc.fixed
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.php
  WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc
  WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc
  WordPress/Tests/Arrays/MultipleStatementAlignmentUnitTest.2.inc.fixed
Labels: Focus: Modern PHP, Status: Review Ready, Type: Bug, Type: Enhancement

#1781 Travis: ignore PHP deprecation notices for stable PHPCS releases
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1784 Various minor doc fixes
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/PHP/IniSetSniff.php
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup, Type: Documentation

#1783 PrefixAllGlobals/GlobalVariablesOverride: detect variables being set via list()
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Labels: Focus: Modern PHP, Status: Review Ready, Type: Enhancement

#1741 Fixes #1733 - Error on short prefixes
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
Labels: Type: Enhancement
