Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-06, with the labels that each got.

#1716 Add wp_sanitize_redirect
  WordPress/Sniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
Labels: Focus: Security, Status: Awaiting Feedback, Type: Enhancement

#1712 ValidHookName: bug fix / skip over array keys
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Labels: Status: Review Ready, Type: Bug

#1718 Add RECOVERY_MODE_COOKIE to whitelisted core constants
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Type: Enhancement

#1753 Travis: add "quicktest" stage for non-PR/merge builds
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1714 RestrictedPHPFunctions: add error for use of date()
  WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php
  WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.inc
  WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.php
Labels: Component: Core, Focus: WP interoperability, Status: Review Ready, Type: Enhancement
