Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-05, with the labels that each got.

#1697 Accept tag_ID as variable name
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
Labels: Type: Enhancement

#1701 Remove paginate_comments_links from escaped functions list
  WordPress/Sniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1699 CapitalPDangit: ignore misspellings in constant declarations
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
Labels: Status: Review Ready, Type: Enhancement

#1706 Sniff::is_test_class(): recognize `TestCase`
  WordPress/Sniff.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.5.inc
Labels: Status: Review Ready, Type: Bug, Type: Enhancement

#1708 Update default minimum_supported_version to WP 4.9
  WordPress/Sniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
  phpcs.xml.dist.sample
Labels: Status: Review Ready, Type: Chores/Cleanup

#1707 Changelog for WPCS 2.1.1
  CHANGELOG.md
Labels: Status: Review Ready, Type: Documentation

#1709 Release version 2.1.1
  CHANGELOG.md
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.5.inc
  phpcs.xml.dist.sample
Labels: Meta: Repo, Status: Review Ready

#1711 Travis: run the code style related and ruleset checks in separate stages
  .travis.yml
Labels: Status: Review Ready
