Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2019-01, with the labels that each got.

#1615 Revert "Extra: Use the new `Generic.WhiteSpace.LanguageConstructSpacing` sniff (PHPCS 3.3.0)"
  WordPress-Extra/ruleset.xml
Labels: Status: Review Ready, Type: Bug, Upstream: PHPCS

#1626 Release version 2.0.0
  CHANGELOG.md
  WordPress-Extra/ruleset.xml
Labels: Meta: Repo, Status: Review Ready

#1628 Bumped suggested installer version
  composer.json
Labels: Type: Chores/Cleanup

#1633 PrefixAllGlobals: prevent false negatives for autoloaded user-defined global functions
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Status: Review Ready, Type: Bug

#1634 ValidatedSanitizedInput: only recognize a variable as validated if the correct variable is examined
  WordPress/Sniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Labels: Status: Review Ready, Type: Bug

#1604 WPCS native PHPCS ruleset: minor tweaks
  .phpcs.xml.dist
Labels: Status: Review Ready, Type: Chores/Cleanup

#1636 Sniff::$test_class_whitelist: add newly added base test class to the list
  WordPress/Sniff.php
Labels: Status: Review Ready, Type: Enhancement
