Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2020-07, with the labels that each got.

#1906 3.0: Travis: simplify the script
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1909 3.0: Remove the WordPress.WP.TimezoneChange sniff
  WordPress/Sniffs/WP/TimezoneChangeSniff.php
  WordPress/Tests/WP/TimezoneChangeUnitTest.inc
  WordPress/Tests/WP/TimezoneChangeUnitTest.php
  WordPress/ruleset.xml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1910 3.0: Replace the `WordPress.CodeAnalysis.EmptyStatement` sniff
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/CodeAnalysis/EmptyStatementSniff.php
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.1.inc.fixed
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.2.inc
  WordPress/Tests/CodeAnalysis/EmptyStatementUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1911 3.0: Replace the `WordPress.PHP.DisallowShortTernary` sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/PHP/DisallowShortTernaryStandard.xml
  WordPress/Sniffs/PHP/DisallowShortTernarySniff.php
  WordPress/Tests/PHP/DisallowShortTernaryUnitTest.inc
  WordPress/Tests/PHP/DisallowShortTernaryUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1912 3.0: Replace the `WordPress.WhiteSpace.DisallowInlineTabs` sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/WhiteSpace/DisallowInlineTabsStandard.xml
  WordPress/Sniffs/WhiteSpace/DisallowInlineTabsSniff.php
  WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc
  WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.inc.fixed
  WordPress/Tests/WhiteSpace/DisallowInlineTabsUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1913 3.0: Tests/RestrictedClasses: compatibility with PHPCS 4.x
  WordPress/Tests/DB/RestrictedClassesUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1914 3.0: TypeCasts: remove sniffing for `T_STRING_CAST`
  WordPress/Sniffs/PHP/TypeCastsSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1908 3.0: Remove deprecated `Sniff::has_whitelist_comment()` method and all references to it
  .github/CONTRIBUTING.md
  .phpcs.xml.dist
  README.md
  WordPress/Sniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Sniffs/DB/SlowDBQuerySniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/PHP/StrictComparisonsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php
  WordPress/Tests/DB/PreparedSQLUnitTest.inc
  WordPress/Tests/DB/PreparedSQLUnitTest.php
  WordPress/Tests/DB/SlowDBQueryUnitTest.inc
  WordPress/Tests/DB/SlowDBQueryUnitTest.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.php
  WordPress/Tests/PHP/StrictComparisonsUnitTest.inc
  WordPress/Tests/PHP/StrictComparisonsUnitTest.php
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.php
  WordPress/Tests/Security/NonceVerificationUnitTest.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
  WordPress/Tests/WP/CapitalPDangitUnitTest.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1918 .gitattributes: minor update
  .gitattributes
Labels: Status: Review Ready, Type: Chores/Cleanup

#1919 3.0: Replace the `WordPress.PHP.StrictComparisons` sniff
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/PHP/StrictComparisonsSniff.php
  WordPress/Tests/PHP/StrictComparisonsUnitTest.inc
  WordPress/Tests/PHP/StrictComparisonsUnitTest.php
  bin/class-ruleset-test.php
Labels: Status: Review Ready, Type: Chores/Cleanup, Type: Enhancement

#1920 3.0: Core: replace `Generic.Arrays.DisallowShortArraySyntax` with `Universal` version
  WordPress-Core/ruleset.xml
Labels: Status: Review Ready, Type: Bug

#1921 3.0: Extra: replace the `Squiz.WhiteSpace.LanguageConstructSpacing` sniff
  WordPress-Extra/ruleset.xml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1922 3.0: Remove the PHPCSHelper class
  WordPress/PHPCSHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/PHP/TypeCastsUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup, Type: Enhancement

#1907 3.0: Tests: add a bootstrap file
  .gitattributes
  Tests/bootstrap.php
  composer.json
  phpunit.xml.dist
Labels: Status: Review Ready, Type: Chores/Cleanup

#1926 3.0: Remove some utility methods from the Sniff class
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
  WordPress/Sniffs/PHP/IniSetSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup, Type: Enhancement

#1924 3.0: Core ruleset: add PHPCSUtils requirement
  WordPress-Core/ruleset.xml
Labels: Meta: Repo, Status: Review Ready

#1925 PHPCS 4.x compatibility: allow for the JS/CSS tokenizer being dropped in PHPCS 4.x
  WordPress/Sniffs/Classes/ClassInstantiationSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Tests/Classes/ClassInstantiationUnitTest.php
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1927 Tests: move ruleset check file to tests directory
  .travis.yml
  Tests/RulesetCheck/class-ruleset-test.inc
Labels: Status: Review Ready, Type: Chores/Cleanup

#1930 OperatorSpacing: defer to upstream for "instanceof"
  WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
  WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
  WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
  WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1928 CastStructureSpacing: minor error message improvement
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
Labels: Status: Review Ready, Type: Enhancement

#1931 3.0: ValidFunctionName: implement PHPCSUtils and more
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
  WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.php
Labels: Status: Review Ready, Type: Bug, Type: Enhancement

#1932 CI: use Parallel-Lint
  .travis.yml
  composer.json
Labels: Status: Review Ready, Type: Chores/Cleanup

#1929 3.0: CapitalPDangit: implement PHPCSUtils and check namespace names
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
  WordPress/Tests/WP/CapitalPDangitUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1934 3.0: EnqueuedResources: PHPCSUtils implementation
  WordPress/Sniffs/WP/EnqueuedResourcesSniff.php
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.php
Labels: Status: Review Ready, Type: Enhancement

#1935 PHP 8 | ControlStructureSpacing: bug fix - $data should be an array
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
Labels: Status: Review Ready, Type: Bug

#1938 ArrayIndentation: bug fix - prevent fixer conflict
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed
Labels: Component: Core, Status: Review Ready, Type: Bug

#1939 EscapeOutput: defensive coding
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
Labels: Status: Review Ready, Type: Bug

#1940 Travis: change from "trusty" to "xenial"
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1936 Move "minimum WP version" related utilities to dedicated `MinimumWPVersionTrait`
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Sniff.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1941 EscapedNotTranslated: use PHPCSUtils `GetTokensAsString`
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Tests/CodeAnalysis/EscapedNotTranslatedUnitTest.inc
Labels: Status: Review Ready, Type: Enhancement
