Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2020-09, with the labels that each got.

#1950 Travis: retry composer install on failure
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1825 Adds documentation for WordPress.WP.EnqueueResourceParameters.
  WordPress/Docs/WP/EnqueuedResourceParametersStandard.xml
Labels: Type: Documentation

#1827 Adds documentation for the WordPress.WP.CapitalPDangit sniff.
  WordPress/Docs/WP/CapitalPDangitStandard.xml
Labels: Status: Review Ready, Type: Documentation
