Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2020-04, with the labels that each got.

#1874 Travis: fix the build
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1876 PreparedSQL: quick fix for namespace separator
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Tests/DB/PreparedSQLUnitTest.inc
Labels: Component: Core, Focus: Security, Status: Review Ready, Type: Bug

#1881 Update default minimum_supported_version to WP 5.1
  WordPress/Sniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Type: Chores/Cleanup

#1883 Clean up the I18n sniff
  WordPress/Sniffs/WP/I18nSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup

#1887 Minor type hint fix
  WordPress/Sniffs/Security/EscapeOutputSniff.php
Labels: Status: Review Ready, Type: Bug
