Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2020-02, with the labels that each got.

#1858 I18n: bug fix - trying to access array offset on null (PHP 7.4)
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Tests/WP/I18nUnitTest.1.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
  WordPress/Tests/WP/I18nUnitTest.php
Labels: Component: Core, Focus: I18n, Priority: High, Status: Review Ready

#1854 Changelog for WPCS 2.2.1
  CHANGELOG.md
Labels: Meta: Repo, Status: Review Ready, Type: Documentation

#1855 Release version 2.2.1
  .travis.yml
  CHANGELOG.md
  README.md
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.6.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
  WordPress/Tests/WP/I18nUnitTest.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
  composer.json
Labels: Meta: Repo, Status: Review Ready

#1857 Travis: various tweaks
  .travis.yml
Labels: Status: Review Ready, Type: Chores/Cleanup

#1867 Travis/QA: always check that all sniffs are feature complete
  .travis.yml
  composer.json
Labels: Status: Review Ready

#1863 AbstractFunctionRestrictions: fix constants being recognized as functions
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Labels: Focus: WP interoperability, Status: Review Ready, Type: Bug

#1856 I18n: Add check to detect string wrapped in HTML
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Tests/WP/I18nUnitTest.1.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
  WordPress/Tests/WP/I18nUnitTest.php
Labels: Component: Core, Focus: I18n, Status: Review Ready, Type: Enhancement

#1869 Correct grammar for wp_reset_query warning
  WordPress/Sniffs/WP/DiscouragedFunctionsSniff.php
Labels: Status: Review Ready, Type: Chores/Cleanup
