Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2021-02, with the labels that each got.

#1965 Move from TravisCI to GitHub Actions
  .gitattributes
  .github/workflows/quicktest.yml
  .github/workflows/ruleset-checks-sniffs.yml
  .github/workflows/unit-tests.yml
  .travis.yml
  README.md
  composer.json
Labels: Priority: High, Status: Review Ready, Type: Chores/Cleanup

#1960 3.0: Move "is unit test" utility functions to dedicated trait
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Sniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends.2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration.4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends.5.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.4.inc
Labels: Status: Review Ready, Type: Enhancement

#1978 Security/EscapeOutput: bug fix - allow for basename() being fully qualified
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
Labels: Focus: Security, Status: Review Ready, Type: Bug
