Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2022-05, with the labels that each got.

#2049 Composer: up the minimum PHPCS version to 3.6.2
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/dependency-change.md
  .github/workflows/quicktest.yml
  .github/workflows/ruleset-checks-sniffs.yml
  .github/workflows/unit-tests.yml
  README.md
  composer.json
Labels: Status: Review Ready, Focus: Modern PHP, Meta: Repo

#2050 IsUnitTestTrait: update test class list
  WordPress/Helpers/IsUnitTestTrait.php
Labels: Type: Enhancement, Status: Review Ready

#1724 Document YodaConditionals you must
  WordPress/Docs/PHP/YodaConditionsStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1727 Docs/WordPress.WhiteSpace.OperatorSpacing
  WordPress/Docs/WhiteSpace/OperatorSpacingStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1740 Add PHP.StrictInArray XML documentation
  WordPress/Docs/PHP/StrictInArrayStandard.xml
Labels: Status: Review Ready, Type: Documentation

#2053 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Status: Review Ready, Type: Documentation, Meta: Repo

#2052 3.0: Move "deprecation" related utilities to dedicated DeprecationHelper + handle PHP 8.0 attributes
  WordPress/Helpers/DeprecationHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
Labels: Type: Enhancement, Status: Review Ready, Focus: Modern PHP
