Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2022-12, with the labels that each got.

#2117 :sparkles: New `WordPress.WP.ClassNameCase` sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/WP/ClassNameCaseStandard.xml
  WordPress/Sniffs/WP/ClassNameCaseSniff.php
  WordPress/Tests/WP/ClassNameCaseUnitTest.inc
  WordPress/Tests/WP/ClassNameCaseUnitTest.php
Labels: Type: Enhancement, Status: Review Ready, Component: Core, Focus: WP interoperability

#2116 Group all the checks in one place and add script descriptions
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
  composer.json
Labels: Type: Enhancement

#2112 Add sniff that will check that capabilities are used correctly.
  WordPress-Extra/ruleset.xml
  WordPress/Docs/WP/CapabilitiesStandard.xml
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Tests/WP/CapabilitiesUnitTest.1.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.2.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.3.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Review Ready, Focus: WP interoperability

#2118 MinimumWPVersionTrait: rename minimum WP version property
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.1.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2120 WP/Capabilities: tests - prevent CLI value leaking
  WordPress/Tests/WP/CapabilitiesUnitTest.4.inc
  WordPress/Tests/WP/CapabilitiesUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2122 CS: minor tweaks/don't allow warnings
  .github/workflows/ruleset-checks-sniffs.yml
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2121 Update the minimum_wp_version to WP 5.8
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
  WordPress/Tests/WP/DeprecatedClassesUnitTest.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review Ready

#2126 Remove outdated `bin/pre-commit` file
  bin/pre-commit
Labels: Type: Chores/Cleanup, Status: Review Ready

#2127 GH Actions: automate some label management
  .github/workflows/manage-labels.yml
Labels: Type: Chores/Cleanup, Status: Review Ready

#2128 Core: add sniffs to check class/constant modifier keyword order
  WordPress-Core/ruleset.xml
Labels: Type: Enhancement, Status: Review Ready, Component: Core

#2130 Core: add sniffs to check formatting of increment/decrement operators
  WordPress-Core/ruleset.xml
  WordPress/Sniff.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review Ready, Component: Core

#2129 Replace the `WordPress.WhiteSpace.PrecisionAlignment` sniff
  WordPress-Core/ruleset.xml
  WordPress/Docs/WhiteSpace/PrecisionAlignmentStandard.xml
  WordPress/Sniffs/WhiteSpace/PrecisionAlignmentSniff.php
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.1.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.2.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.3.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.4.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.5.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.6.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7a.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7b.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.7c.inc
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.css
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.js
  WordPress/Tests/WhiteSpace/PrecisionAlignmentUnitTest.php
Labels: Type: Bug, Status: Review Ready, Component: Core

#2133 Core: move rules related to object instantiations from Extra to Core
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/Classes/ClassInstantiationSniff.php
  WordPress/Tests/Classes/ClassInstantiationUnitTest.inc
  WordPress/Tests/Classes/ClassInstantiationUnitTest.inc.fixed
  WordPress/Tests/Classes/ClassInstantiationUnitTest.js
  WordPress/Tests/Classes/ClassInstantiationUnitTest.js.fixed
  WordPress/Tests/Classes/ClassInstantiationUnitTest.php
Labels: Type: Enhancement, Status: Review Ready, Component: Core

#2132 Core: add sniffs to check formatting for type declarations
  WordPress-Core/ruleset.xml
Labels: Type: Enhancement, Status: Review Ready, Component: Core

#2131 GH Actions: tweak label management workflow
  .github/workflows/manage-labels.yml
Labels: Type: Chores/Cleanup, Status: Review Ready

#2134 Core: add sniff to discourage using reserved keywords as param names
  WordPress-Core/ruleset.xml
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
Labels: Type: Enhancement, Status: Review Ready, Component: Core

#2139 PHP/PregQuoteDelimiter: add support for PHP 8.0+ named parameters
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.inc
  WordPress/Tests/PHP/PregQuoteDelimiterUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Review Ready

#2138 WP/DeprecatedParameters: add support for PHP 8.0+ named parameters
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Review Ready

#2137 Core: add sniff to enforce the use of __DIR__ instead of dirname(__FILE__)
  WordPress-Core/ruleset.xml
Labels: Status: Review Ready, Focus: Modern PHP, Component: Core

#2136 Core: ensure more keywords are lowercase
  WordPress-Core/ruleset.xml
Labels: Status: Review Ready, Component: Core

#2140 PHP/StrictInArray: add support for PHP 8.0+ named parameters
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Tests/PHP/StrictInArrayUnitTest.inc
  WordPress/Tests/PHP/StrictInArrayUnitTest.php
Labels: Type: Enhancement, Status: Review Ready, Component: Core

#2142 GH Actions: various tweaks / add PHP 8.3
  .github/workflows/basic-qa.yml
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
Labels: Type: Chores/Cleanup, Status: Review Ready

#2144 QA: URL review across codebase
  .gitattributes
  CHANGELOG.md
  README.md
  WordPress-Docs/ruleset.xml
  WordPress/Docs/PHP/YodaConditionsStandard.xml
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Sniffs/DB/RestrictedClassesSniff.php
  WordPress/Sniffs/DB/RestrictedFunctionsSniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/PHP/DiscouragedPHPFunctionsSniff.php
  WordPress/Sniffs/PHP/DontExtractSniff.php
  WordPress/Sniffs/PHP/POSIXFunctionsSniff.php
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Sniffs/PHP/TypeCastsSniff.php
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayIndentationUnitTest.2.inc.fixed
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.3.inc
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.3.inc.fixed
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.css
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.css.fixed
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.inc.fixed
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc
  WordPress/Tests/WP/I18nUnitTest.1.inc.fixed
Labels: Status: Review Ready, Type: Documentation

#2143 Extra: add additional rules
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
Labels: Component: Extra, Type: Enhancement, Focus: Code Analysis

#2146 WP/EnqueuedResourceParameters: change `MissingVersion` to a warning
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Review Ready

#2145 Sniff::$formattingFunctions: add `antispambot()` to the list
  WordPress/Sniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.php
Labels: Type: Enhancement, Status: Review Ready, Focus: Security

#2149 MinimumWPVersionTrait: add new `wp_version_compare()` method (bug fix)
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
Labels: Type: Bug, Status: Review Ready

#2148 New `WPHookHelper` utility class, incl PHP 8.0+ named param helper
  WordPress/Helpers/WPHookHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2153 WhiteSpace/OperatorSpacing: add extra tests with PHP 8.0+ types
  WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
  WordPress/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Labels: Type: Chores/Cleanup, Status: Review Ready

#2152 PHP/YodaConditions: implement PHPCSUtils + more tweaks
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Component: Core

#2151 Arrays/CommaAfterArrayItem: minor tweaks
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Component: Core

#2150 Arrays/ArrayKeySpacingRestrictions: small bug fix
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
Labels: Type: Bug, Status: Review Ready, Component: Core

#2156 Sniff: move the `$cache*Functions` properties to the `DB/DirectDatabaseQuery` Sniff
  WordPress/Sniff.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2155 Sniff: move the `has_nonce_check()` method to the `Security/NonceVerification` Sniff
  WordPress/Sniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2158 Move "is WPDB method call" related utilities to dedicated WPDBTrait + improve
  WordPress/Helpers/WPDBTrait.php
  WordPress/Sniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/PreparedSQLSniff.php
  WordPress/Tests/DB/PreparedSQLUnitTest.inc
  WordPress/Tests/DB/PreparedSQLUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Status: Review Ready, Focus: Modern PHP

#2157 Move "property handling" related utilities to dedicated `RulesetPropertyHelper`
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Helpers/RulesetPropertyHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2108 Updated - WP.AlternativeFunctions: Add more functions to filesystem functions list
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Awaiting Feedback, Focus: WP interoperability

#2159 Move "global variable" related utilities to dedicated `WPGlobalVariablesHelper`
  WordPress/Helpers/WPGlobalVariablesHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2163 PHP/StrictInArray: prevent some false positives
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Tests/PHP/StrictInArrayUnitTest.inc
Labels: Type: Bug, Status: Review Ready

#2162 PHP/NoSilencedErrors: implement PHPCSUtils methods
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.inc
  WordPress/Tests/PHP/NoSilencedErrorsUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2161 PHP/IniSet: add support for PHP 8.0+ named parameters + bug fix
  WordPress/Sniffs/PHP/IniSetSniff.php
  WordPress/Tests/PHP/IniSetUnitTest.inc
  WordPress/Tests/PHP/IniSetUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Status: Review Ready, Focus: Modern PHP

#2160 DateTime/CurrentTimeTimestamp: add support for PHP 8.0+ named parameters + minor tweak
  WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.inc.fixed
  WordPress/Tests/DateTime/CurrentTimeTimestampUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Focus: Modern PHP

#2168 Security/PluginMenuSlug: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Tests/Security/PluginMenuSlugUnitTest.inc
  WordPress/Tests/Security/PluginMenuSlugUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review Ready, Focus: Modern PHP

#2170 WP/CapitalPDangit: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed
  WordPress/Tests/WP/CapitalPDangitUnitTest.2.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.2.inc.fixed
  WordPress/Tests/WP/CapitalPDangitUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Focus: Modern PHP, Component: Core

#2167 NamingConventions/ValidPostTypeSlug: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
  WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.2.inc
  WordPress/Tests/NamingConventions/ValidPostTypeSlugUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review Ready, Focus: Modern PHP

#2166 NamingConventions/ValidHookName: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Status: Review Ready, Focus: Modern PHP, Component: Core

#2165 Move "is assignment" related utility to dedicated `VariableHelper`
  WordPress/Helpers/VariableHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2169 WP/AlternativeFunctions: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.inc
  WordPress/Tests/WP/AlternativeFunctionsUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2172 WP/CronInterval: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Tests/WP/CronIntervalUnitTest.inc
  WordPress/Tests/WP/CronIntervalUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2173 WP/DeprecatedParameters: verify against WP Core
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready

#2175 WP/DiscouragedConstants: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc
  WordPress/Tests/WP/DiscouragedConstantsUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2174 WP/DeprecatedParameterValues: support modern PHP + update for WP 6.1
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2177 WP/EnqueuedResourceParameters: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.inc
  WordPress/Tests/WP/EnqueuedResourceParametersUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2176 WP/EnqueuedResources: various tweaks
  WordPress/Sniffs/WP/EnqueuedResourcesSniff.php
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.1.inc
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.2.inc
  WordPress/Tests/WP/EnqueuedResourcesUnitTest.php
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review Ready, Focus: Modern PHP

#2178 Various sniffs: improve error messages
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php
  WordPress/Sniffs/PHP/TypeCastsSniff.php
  WordPress/Sniffs/Security/SafeRedirectSniff.php
Labels: Status: Review Ready, Type: Documentation

#2181 WP/GlobalVariablesOverride: implement PHPCSUtils and support modern PHP
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
Labels: Component: Extra, Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP
