Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2022-08, with the labels that each got.

#2074 WP/CronInterval: update inline annotations in test case file
  WordPress/Tests/WP/CronIntervalUnitTest.inc
Labels: Type: Chores/Cleanup, Status: Review Ready

#2073 WP/CronInterval: bugfix for fully qualified time constants
  WordPress/Sniffs/WP/CronIntervalSniff.php
  WordPress/Tests/WP/CronIntervalUnitTest.inc
  WordPress/Tests/WP/CronIntervalUnitTest.php
Labels: Component: Extras, Type: Bug, Status: Review Ready, Focus: Modern PHP

#2075 Arrays/ArrayKeySpacingRestrictions: implement PHPCSUtils and various bug fixes and other improvements
  WordPress/Sniffs/Arrays/ArrayKeySpacingRestrictionsSniff.php
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.inc.fixed
  WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review Ready, Component: Core

#2076 Reorder core rules
  WordPress-Core/ruleset.xml
Labels: Type: Documentation, Component: Core

#2080 Update composer.json keywords
  composer.json
Labels: Status: Review Ready
