Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2022-06, with the labels that each got.

#1726 Prefix Your Globals
  WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml
Labels: Status: Review Ready, Type: Documentation

#1731 Docs: Add TimezoneChange XML doc
  WordPress/Docs/DateTime/RestrictedFunctionsStandard.xml
Labels: Status: Review Ready, Type: Documentation

#2056 NamingConventions/ValidHookName: bug fix - ignore parameters passed to function calls
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.1.inc
  WordPress/Tests/NamingConventions/ValidHookNameUnitTest.php
Labels: Type: Bug, Status: Review Ready, Component: Core

#2058 Composer: up the minimum PHPCS version to 3.7.0
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/dependency-change.md
  .github/workflows/quicktest.yml
  .github/workflows/ruleset-checks-sniffs.yml
  .github/workflows/unit-tests.yml
  README.md
  composer.json
Labels: Meta: Repo

#2062 3.0: Move "variable" related utilities to dedicated VariableHelper + use PHPCSUtils + handle match
  WordPress/Helpers/VariableHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.inc
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Labels: Type: Enhancement, Status: Review Ready, Focus: Modern PHP

#2061 Helper classes: explicitly state there is no BC promise
  WordPress/Helpers/DeprecationHelper.php
  WordPress/Helpers/TextStringHelper.php
Labels: Status: Review Ready, Type: Documentation, Meta: Repo

#2063 DB/DirectDatabaseQuery: remove custom ignore annotation support
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2067 Add link to "Running in GitHub Actions" doc page
  README.md
Labels: Type: Documentation
