Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2023-08, with the labels that each got.

#2330 Composer: make PHP extension dependencies explicit
  composer.json
Labels: Status: Review ready, Type: Documentation

#2328 Core: properly check formatting of function declaration statements
  .github/workflows/basic-qa.yml
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.7.inc
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready, Component: Core

#2329 Add release checklist
  .github/release-checklist.md
Labels: Status: Review ready, Type: Documentation, Meta: Repo

#2333 Whitespace/ControlStructureSpacing: sync with upstream + minor tweaks
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.1.inc.fixed
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready, Focus: Modern PHP, Component: Core

#2335 Docs: remove orphaned docs
  WordPress/Docs/Arrays/CommaAfterArrayItemStandard.xml
  WordPress/Docs/Classes/ClassInstantiationStandard.xml
Labels: Type: Chores/Cleanup, Status: Review ready, Type: Documentation

#2334 WhiteSpace/ControlStructureSpacing: add documentation
  WordPress/Docs/WhiteSpace/ControlStructureSpacingStandard.xml
Labels: Status: Review ready, Type: Documentation, Component: Core

#2336 Docs: update the sample ruleset
  phpcs.xml.dist.sample
Labels: Status: Review ready, Type: Documentation

#2338 Code coverage: initial setup for CodeCov
  .codecov.yml
  .gitattributes
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
  README.md
  phpunit.xml.dist
Labels: Type: Chores/Cleanup, Status: Review ready

#2345 Docs: array properties expect arrays
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready, Type: Documentation

#2344 WhiteSpace/ControlStructureSpacing: minor defensive coding tweak
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.2.inc
  WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.2.inc.fixed
Labels: Type: Chores/Cleanup, Status: Review ready

#2343 Files/FileName: minor defensive coding tweak in test code
  WordPress/Tests/Files/FileNameUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2342 DB/DirectDatabaseQuery: minor defensive coding tweak
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
Labels: Type: Chores/Cleanup, Status: Review ready

#2341 DateTime/CurrentTimeTimestamp: rename some local variables
  WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2340 WP/Capabilities: minor clean up
  WordPress/Sniffs/WP/CapabilitiesSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2339 Utils/I18nTextDomainFixer: use PHPCSUtils in one more place
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2348 README: fix codecov badge
  README.md
Labels: Status: Review ready, Type: Documentation

#2347 Sniff: move "missing unslashing" handling to callback function
  WordPress/Sniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready, Component: Helpers

#2356 Move sanitization methods to SanitizationHelperTrait + minor improvements
  WordPress/Helpers/SanitizationHelperTrait.php
  WordPress/Sniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready, Component: Helpers

#2350 GH Actions: fix quicktest for `develop`
  .github/workflows/quicktest.yml
Labels: Type: Chores/Cleanup, Status: Review ready

#2351 Issue template: minor tweaks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/dependency-change.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Status: Review ready, Type: Documentation

#2352 Changelog: update references to the Composer PHPCS plugin
  CHANGELOG.md
Labels: Status: Review ready, Type: Documentation

#2353 Codecov config: tweak patch config
  .codecov.yml
Labels: Type: Chores/Cleanup, Status: Review ready

#2354 QA/CS: various minor tweaks
  WordPress/Helpers/ConstantsHelper.php
  WordPress/Helpers/EscapingFunctionsTrait.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/WP/CapitalPDangitSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2355 Add PHPStan to QA checks
  .gitattributes
  .github/workflows/basic-qa.yml
  .gitignore
  phpstan.neon.dist
Labels: Type: Chores/Cleanup, Status: Review ready

#2360 Updates related to branch rename from `master` to `main`
  .github/CONTRIBUTING.md
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  README.md
Labels: Type: Chores/Cleanup, Status: Review ready, Type: Documentation, Meta: Repo

#2361 Make methods in traits `final`
  .phpcs.xml.dist
  WordPress/Helpers/EscapingFunctionsTrait.php
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Helpers/PrintingFunctionsTrait.php
  WordPress/Helpers/SanitizationHelperTrait.php
  WordPress/Helpers/WPDBTrait.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2363 CS: closures not using `$this` should be static
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/DB/PreparedSQLSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2362 Security/ValidatedSanitizedInput: use PHPCSutils and bug fixes
  WordPress/Helpers/ValidationHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.1.inc
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.php
Labels: Type: Bug, Type: Enhancement, Status: Review ready, Focus: Security

#2365 Helpers: add type declarations whenever possible
  WordPress/Helpers/RulesetPropertyHelper.php
  WordPress/Helpers/WPDBTrait.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2364 Sniff: remove `init()` method
  WordPress/Sniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2367 Update documentation (README, CONTRIBUTING) for release of WordPressCS 3.0.0
  .gitattributes
  .github/CONTRIBUTING.md
  .phpcs.xml.dist
  README.md
  Tests/RulesetCheck/class-ruleset-test.inc
Labels: Status: Review ready, Type: Documentation

#2366 Tests: Remove redundant placeholder function
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
Labels: Type: Chores/Cleanup, Status: Review ready
