Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2023-12, with the labels that each got.

#2409 Use two new sniffs from PHPCSExtra 1.2.0
  .github/CONTRIBUTING.md
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
  composer.json
Labels: Component: Extra, Type: Enhancement, Status: Review ready, Component: Core

#2410 Update funding information
  .github/FUNDING.yml
  README.md
Labels: Status: Review ready, Type: Documentation

#2412 PHPStan: ignore two new issues
  phpstan.neon.dist
Labels: Type: Chores/Cleanup, Status: Review ready

#2408 Switch to PHPCSStandards/PHP_CodeSniffer & raise minimum supported version
  .github/CONTRIBUTING.md
  .github/release-checklist.md
  .phpcs.xml.dist
  CHANGELOG.md
  README.md
  WordPress-Core/ruleset.xml
  WordPress-Docs/ruleset.xml
  WordPress-Extra/ruleset.xml
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
  WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/ruleset.xml
  composer.json
  phpcs.xml.dist.sample
Labels: Meta: Repo

#2397 Add sanitize_locale_name() to escaping functions and unslashing sanitizing functions
  WordPress/Helpers/EscapingFunctionsTrait.php
  WordPress/Helpers/SanitizationHelperTrait.php
Labels: Component: Extra, Type: Enhancement, Focus: Security

#2415 Core: remove an exclusion
  WordPress-Core/ruleset.xml
Labels: Type: Enhancement, Status: Review ready, Component: Core

#2414 Tests: allow for PHPUnit 8/9
  .github/CONTRIBUTING.md
  .github/workflows/basic-qa.yml
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
  .gitignore
  WordPress/Tests/DB/RestrictedClassesUnitTest.php
  composer.json
  phpstan.neon.dist
  phpunit.xml.dist
Labels: Type: Chores/Cleanup, Status: Review ready

#2418 Fix the test case file path used in a CONTRIBUTING.md example
  .github/CONTRIBUTING.md
Labels: Status: Review ready, Type: Documentation
