Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2023-07, with the labels that each got.

#2278 WP/DiscouragedConstants: use the `ConstantsHelper` class
  WordPress/Helpers/ConstantsHelper.php
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Tests/WP/DiscouragedConstantsUnitTest.inc
Labels: Type: Chores/Cleanup, Type: Bug, Status: Review Ready

#2277 NamingConventions/ValidVariableName: re-order member names + remove one
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2276 NamingConventions/PrefixAllGlobals: make the "is PHP native polyfill ?" check case-insensitive
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
Labels: Type: Bug, Status: Review Ready

#2275 Security/PluginMenuSlug: order functions list alphabetically
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2273 Helpers: make sure function names are checked case-insensitively
  WordPress/Helpers/ArrayWalkingFunctionsHelper.php
  WordPress/Helpers/EscapingFunctionsTrait.php
  WordPress/Helpers/FormattingFunctionsHelper.php
  WordPress/Helpers/PrintingFunctionsTrait.php
  WordPress/Helpers/SanitizingFunctionsTrait.php
  WordPress/Helpers/UnslashingFunctionsHelper.php
  WordPress/Tests/DB/PreparedSQLUnitTest.1.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/Security/ValidatedSanitizedInputUnitTest.1.inc
Labels: Type: Bug, Status: Review Ready, Component: Helpers

#2271 ContextHelper::$safe_casts: make `private`
  WordPress/Helpers/ContextHelper.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Component: Helpers

#2270 PHP/StrictInArray: rename a local variable
  WordPress/Sniffs/PHP/StrictInArraySniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready

#2268 Improve consistency in method names across Helpers
  WordPress/Helpers/ArrayWalkingFunctionsHelper.php
  WordPress/Helpers/UnslashingFunctionsHelper.php
  WordPress/Sniff.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Component: Helpers

#2267 Helpers\IsUnitTestTrait: bug fix - allow for custom test classes passed as FQN
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit.5.inc
Labels: Type: Bug, Type: Enhancement, Status: Review Ready, Focus: Modern PHP, Component: Helpers

#2269 Helpers: add some more defensive coding
  WordPress/Helpers/ContextHelper.php
  WordPress/Helpers/DeprecationHelper.php
  WordPress/Helpers/ListHelper.php
  WordPress/Helpers/ValidationHelper.php
  WordPress/Helpers/VariableHelper.php
  WordPress/Helpers/WPDBTrait.php
Labels: Type: Chores/Cleanup, Status: Review Ready, Component: Helpers

#2283 WP/AlternativeFunctionsSniff::is_local_data_stream(): update param name and docs
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2282 Docs: remove redundant comment
  WordPress/Helpers/MinimumWPVersionTrait.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2281 Docs: use correct format for `@internal` tags
  WordPress/Helpers/ContextHelper.php
  WordPress/Helpers/ListHelper.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
Labels: Status: Review ready, Type: Documentation

#2280 Docs: clarify the `$matched_content` parameter
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Sniffs/CodeAnalysis/EscapedNotTranslatedSniff.php
  WordPress/Sniffs/DateTime/CurrentTimeTimestampSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
  WordPress/Sniffs/PHP/IniSetSniff.php
  WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php
  WordPress/Sniffs/PHP/StrictInArraySniff.php
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/ClassNameCaseSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Sniffs/WP/DiscouragedConstantsSniff.php
  WordPress/Sniffs/WP/EnqueuedResourceParametersSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready, Type: Documentation

#2284 IsUnitTestTrait: make sure namespace and class names are checked case-insensitively
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-phpunit6-case-insensitive.inc
Labels: Type: Bug, Status: Review ready, Component: Helpers

#2285 Files/FileName: various improvements
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit-1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit-2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit-3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit-4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-custom-unit-5.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends-1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-global-namespace-extends-2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration-1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration-2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration-3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-declaration-4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends-1.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends-2.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends-3.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends-4.inc
  WordPress/Tests/Files/FileNameUnitTests/TestFiles/test-sample-namespaced-extends-5.inc
  WordPress/Tests/Files/FileNameUnitTests/class-file-with-different-extension.php3
  WordPress/Tests/Files/FileNameUnitTests/class-wrong-with-different-extension.php3
  WordPress/Tests/Files/FileNameUnitTests/class.with.dot.not.underscore.inc
  WordPress/Tests/Files/FileNameUnitTests/class.wp-dependencies.inc
  WordPress/Tests/Files/FileNameUnitTests/class.wp-scripts.inc
  WordPress/Tests/Files/FileNameUnitTests/class.wp-styles.inc
  WordPress/Tests/Files/FileNameUnitTests/class@with#other+punctuation.inc
Labels: Type: Bug, Type: Enhancement, Status: Review ready

#2286 NamingConventions/PrefixAllGlobals: allow non-prefixed declarations for pluggable functions and classes
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
Labels: Type: Bug, Type: Enhancement, Status: Review ready, Focus: WP interoperability

#2266 AbstractArrayAssignmentRestrictions: implement PHPCSUtils, bug fixes, modern PHP and more
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/Tests/WP/PostsPerPageUnitTest.inc
  WordPress/Tests/WP/PostsPerPageUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review ready, Focus: Modern PHP

#2287 GH Actions/manage-labels: remove label which doesn't exist anymore
  .github/workflows/manage-labels.yml
Labels: Type: Chores/Cleanup, Status: Review ready

#2288 DB/DirectDatabaseQuery: 2 fixes for case-insensitivity (PHP + SQL)
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.php
Labels: Type: Bug, Status: Review ready, Focus: DB

#2290 Always use BCFile for find[Start|End]OfStatement()
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/Sniffs/CodeAnalysis/AssignmentInTernaryConditionSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2291 AbstractArrayAssignmentRestrictions: remove support for 'callback'
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2289 WP/PostsPerPage: various bug fixes
  WordPress/Sniffs/WP/PostsPerPageSniff.php
  WordPress/Tests/WP/PostsPerPageUnitTest.inc
  WordPress/Tests/WP/PostsPerPageUnitTest.php
Labels: Type: Bug, Status: Review ready, Focus: Modern PHP

#2295 Docs: make sure all moved methods have correct changelog entries
  WordPress/Helpers/ConstantsHelper.php
  WordPress/Helpers/ContextHelper.php
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Helpers/ListHelper.php
  WordPress/Helpers/SnakeCaseHelper.php
  WordPress/Helpers/ValidationHelper.php
  WordPress/Helpers/VariableHelper.php
  WordPress/Helpers/WPDBTrait.php
  WordPress/Helpers/WPHookHelper.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
Labels: Status: Review ready, Type: Documentation

#2293 Docs: add `@internal` tag to classes marked as internal API
  WordPress/Helpers/ConstantsHelper.php
  WordPress/Helpers/ContextHelper.php
  WordPress/Helpers/DeprecationHelper.php
  WordPress/Helpers/ListHelper.php
  WordPress/Helpers/RulesetPropertyHelper.php
  WordPress/Helpers/SnakeCaseHelper.php
  WordPress/Helpers/VariableHelper.php
Labels: Status: Review ready, Type: Documentation

#2296 VariableHelper::is_comparison(): minor defensive coding tweak
  WordPress/Helpers/VariableHelper.php
Labels: Type: Bug, Status: Review ready, Component: Helpers

#2297 Security/NonceVerification: use PHPCSUtils, modern PHP + other bug fixes
  WordPress/Helpers/VariableHelper.php
  WordPress/Sniffs/Security/NonceVerificationSniff.php
  WordPress/Tests/Security/NonceVerificationUnitTest.1.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.2.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.3.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.4.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.5.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.6.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.7.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.8.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.php
Labels: Type: Chores/Cleanup, Type: Bug, Type: Enhancement, Status: Review ready, Focus: Modern PHP, Focus: Security

#2300 NamingConventions/ValidVariableName: bring back `$catID`
  WordPress/Sniffs/NamingConventions/ValidVariableNameSniff.php
  WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
Labels: Type: Bug, Status: Review ready, Component: Core

#2301 Arrays/ArrayDeclarationSpacing: partially replace the sniff + implement PHPCSUtils in what remains
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.1.inc.fixed
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.2.inc.fixed
  WordPress/Tests/Arrays/ArrayDeclarationSpacingUnitTest.php
  composer.json
Labels: Type: Bug, Type: Enhancement, Status: Review ready, Focus: Modern PHP, Component: Core

#2307 Composer: update PHPCSUtils + PHPCSExtra
  composer.json
Labels: Type: Enhancement, Status: Review ready

#2310 Replace the WordPress.Array.CommaAfterArrayItem sniff
  WordPress-Core/ruleset.xml
  WordPress/Sniffs/Arrays/CommaAfterArrayItemSniff.php
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.inc.fixed
  WordPress/Tests/Arrays/CommaAfterArrayItemUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready, Component: Core

#2309 Extra: add sniff to detect inefficient "echo sprintf(...)"
  WordPress-Extra/ruleset.xml
Labels: Component: Extra, Type: Enhancement, Status: Review ready

#2308 Core: add some more sniffs for import `use` statements
  WordPress-Core/ruleset.xml
Labels: Type: Enhancement, Status: Review ready, Focus: Modern PHP, Component: Core

#2312 Rulesets: various minor tweaks
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review ready, Component: Core

#2072 Support '%i' placeholders for escaping Identifiers
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php
Labels: Type: Enhancement, Component: Core, Focus: Security, Focus: DB

#2313 Docs: various minor tweaks
  WordPress/Helpers/IsUnitTestTrait.php
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Helpers/ValidationHelper.php
  WordPress/Helpers/VariableHelper.php
  WordPress/Sniffs/DB/SlowDBQuerySniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/WP/ClassNameCaseSniff.php
  WordPress/Sniffs/WP/EnqueuedResourcesSniff.php
  WordPress/Sniffs/WP/PostsPerPageSniff.php
  WordPress/Sniffs/WhiteSpace/OperatorSpacingSniff.php
Labels: Status: Review ready, Type: Documentation

#2320 WP/DeprecatedParameters: update the list based on WP 6.3-RC1
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2319 WP/DeprecatedFunctions: update the functions list based on WP 6.3-RC1
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2318 WP/DeprecatedClasses: update the class list based on WP 6.3-RC1
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
  WordPress/Tests/WP/DeprecatedClassesUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2317 WP/ClassNameCase: update the class lists based on WP 6.3-RC1
  WordPress/Sniffs/WP/ClassNameCaseSniff.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready

#2316 NamingConventions/ValidPostTypeSlug: update the reserved post types list
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2315 NamingConventions/PrefixAllGlobals: update the constants list
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2314 DB/PreparedSQLPlaceholders: use PHPCSUtils, allow for modern PHP and some bug fixes
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.php
Labels: Type: Bug, Type: Enhancement, Status: Review ready, Focus: Modern PHP, Component: Core, Focus: DB

#2321 Update the `minimum_wp_version` to WP 6.0
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2324 Core/Extra: tweak the inclusion of the `Modernize.FunctionCalls.Dirname` sniff
  .phpcs.xml.dist
  WordPress-Core/ruleset.xml
  WordPress-Extra/ruleset.xml
Labels: Component: Extra, Type: Enhancement, Status: Review ready, Component: Core

#2325 Update various function lists
  WordPress/Helpers/EscapingFunctionsTrait.php
  WordPress/Helpers/SanitizingFunctionsTrait.php
Labels: Type: Enhancement, Status: Review ready, Focus: Security, Component: Helpers

#2326 Security/EscapeOutput: use PHPCSUtils, allow for modern PHP and slew of bug fixes
  WordPress/Helpers/PrintingFunctionsTrait.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.1.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.10.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.11.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.12.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.13.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.14.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.15.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.16.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.17.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.18.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.19.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.2.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.20.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.3.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.4.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.5.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.6.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.7.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.8.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.9.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.php
Labels: Component: Extra, Type: Bug, Type: Enhancement, Status: Review ready, Focus: Modern PHP, Focus: Security
