Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2023-09, with the labels that each got.

#2377 GH Actions: add task to test example ruleset
  .github/workflows/basic-qa.yml
  Tests/RulesetCheck/example-ruleset-test.inc
Labels: Type: Chores/Cleanup, Status: Review ready

#2372 Add funding to the readme and add funding file
  .github/FUNDING.yml
  README.md
Labels: Type: Documentation

#2382 Funding: fix format
  .github/FUNDING.yml
Labels: Status: Review ready, Type: Documentation

#2383 Release checklist: add link to monthly dev blog
  .github/release-checklist.md
Labels: Status: Review ready, Type: Documentation

#2378 Security/EscapeOutputSniff: More modular error codes
  WordPress/Sniffs/Security/EscapeOutputSniff.php
Labels: Component: Extra, Type: Enhancement, Focus: Security

#2385 Add changelog for v3.0.1
  CHANGELOG.md
Labels: Type: Documentation, Meta: Repo

#2386 Release WordPressCS 3.0.1
  .github/FUNDING.yml
  .github/release-checklist.md
  .github/workflows/basic-qa.yml
  CHANGELOG.md
  README.md
  Tests/RulesetCheck/example-ruleset-test.inc
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  phpcs.xml.dist.sample
Labels: Meta: Repo

#2384 Add dependabot configuration file
  .github/dependabot.yml
Labels: Type: Chores/Cleanup

#2388 Fix the release date in the changelog
  CHANGELOG.md
Labels: Meta: Repo

#2392 Add defensive coding in posts per page sniff
  WordPress/Sniffs/WP/PostsPerPageSniff.php
  WordPress/Tests/DB/SlowDBQueryUnitTest.inc
  WordPress/Tests/DB/SlowDBQueryUnitTest.php
  WordPress/Tests/WP/PostsPerPageUnitTest.inc
Labels: Type: Bug

#2393 README: minor tweak
  README.md
Labels: Status: Review ready, Type: Documentation
