Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2024-07, with the labels that each got.

#2454 [Documentation]: WordPress.DB.PreparedSQL
  WordPress/Docs/DB/PreparedSQLStandard.xml
Labels: Status: Review ready, Type: Documentation, Component: Core, Focus: DB

#2468 Documentation: various consistency fixes
  WordPress/Docs/Arrays/ArrayIndentationStandard.xml
  WordPress/Docs/Arrays/ArrayKeySpacingRestrictionsStandard.xml
  WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml
  WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml
  WordPress/Docs/PHP/IniSetStandard.xml
  WordPress/Docs/PHP/YodaConditionsStandard.xml
  WordPress/Docs/WP/CapabilitiesStandard.xml
  WordPress/Docs/WP/CapitalPDangitStandard.xml
  WordPress/Docs/WP/DeprecatedParametersStandard.xml
  WordPress/Docs/WP/PostsPerPageStandard.xml
  WordPress/Docs/WhiteSpace/ObjectOperatorSpacingStandard.xml
Labels: Status: Review ready, Type: Documentation

#2469 Documentation: capitalization consistency fixes
  WordPress/Docs/Arrays/MultipleStatementAlignmentStandard.xml
  WordPress/Docs/DateTime/CurrentTimeTimestampStandard.xml
  WordPress/Docs/NamingConventions/PrefixAllGlobalsStandard.xml
  WordPress/Docs/NamingConventions/ValidFunctionNameStandard.xml
  WordPress/Docs/NamingConventions/ValidHookNameStandard.xml
  WordPress/Docs/NamingConventions/ValidPostTypeSlugStandard.xml
  WordPress/Docs/PHP/IniSetStandard.xml
  WordPress/Docs/PHP/StrictInArrayStandard.xml
  WordPress/Docs/WP/CapabilitiesStandard.xml
  WordPress/Docs/WP/ClassNameCaseStandard.xml
  WordPress/Docs/WP/DeprecatedClassesStandard.xml
  WordPress/Docs/WP/DeprecatedFunctionsStandard.xml
  WordPress/Docs/WP/DeprecatedParameterValuesStandard.xml
  WordPress/Docs/WP/DeprecatedParametersStandard.xml
  WordPress/Docs/WhiteSpace/CastStructureSpacingStandard.xml
  WordPress/Docs/WhiteSpace/OperatorSpacingStandard.xml
Labels: Type: Chores/Cleanup, Status: Review ready, Type: Documentation
