Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2024-08, with the labels that each got.

#2472 Fix typos
  CHANGELOG.md
  WordPress-Docs/ruleset.xml
  WordPress/AbstractClassRestrictionsSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Docs/Arrays/ArrayIndentationStandard.xml
  WordPress/Helpers/ContextHelper.php
  WordPress/Helpers/SanitizationHelperTrait.php
  WordPress/Sniffs/Arrays/ArrayIndentationSniff.php
  WordPress/Sniffs/Arrays/MultipleStatementAlignmentSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/Security/PluginMenuSlugSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/GlobalVariablesOverrideSniff.php
  WordPress/Sniffs/WP/I18nSniff.php
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.inc
  WordPress/Tests/DB/PreparedSQLPlaceholdersUnitTest.inc
  WordPress/Tests/DB/PreparedSQLUnitTest.1.inc
  WordPress/Tests/DB/RestrictedFunctionsUnitTest.php
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.8.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.1.inc
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.4.inc.fixed
  phpcs.xml.dist.sample
Labels: Type: Chores/Cleanup, Type: Documentation

#2477 Fix typo in AbstractFunctionRestrictionsSniff::is_targetted_token() DocBlock
  WordPress/AbstractFunctionRestrictionsSniff.php
Labels: Status: Review ready, Type: Documentation

#2465 ✨ New WordPress.WP.GetMetaSingle sniff
  WordPress-Extra/ruleset.xml
  WordPress/Docs/WP/GetMetaSingleStandard.xml
  WordPress/Sniffs/WP/GetMetaSingleSniff.php
  WordPress/Tests/WP/GetMetaSingleUnitTest.inc
  WordPress/Tests/WP/GetMetaSingleUnitTest.php
Labels: Component: Extra, Type: Enhancement, Status: Review ready
