Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2025-07, with the labels that each got.

#2540 Fix the class description for ConstantsHelper and ListHelper
  WordPress/Helpers/ConstantsHelper.php
  WordPress/Helpers/ListHelper.php
Labels: Type: Documentation, Component: Helpers

#2541 Update parameter description for `$stackPtr` in `ConstantsHelper::is_use_of_global_constant()`
  WordPress/Helpers/ConstantsHelper.php
Labels: Status: Review ready, Type: Documentation, Component: Helpers

#2545 Docs: improve type specificity
  WordPress/AbstractFunctionParameterSniff.php
  WordPress/Sniffs/NamingConventions/ValidHookNameSniff.php
  WordPress/Sniffs/PHP/IniSetSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2548 Tests: remove unnecessary trailing spaces from the test files
  WordPress/Tests/DB/RestrictedClassesUnitTest.2.inc
  WordPress/Tests/DB/RestrictedClassesUnitTest.3.inc
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.9.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.1.inc
  WordPress/Tests/Security/NonceVerificationUnitTest.5.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed
Labels: Type: Chores/Cleanup, Status: Review ready

#2547 PHP 8.3 typed class constants: add tests to two sniffs
  WordPress/Tests/NamingConventions/PrefixAllGlobalsUnitTest.1.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc
  WordPress/Tests/WP/CapitalPDangitUnitTest.1.inc.fixed
Labels: Type: Chores/Cleanup, Status: Review ready, Focus: Modern PHP, Component: Core

#2537 Update list based sniffs for WP 6.8.1
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidPostTypeSlugSniff.php
  WordPress/Sniffs/WP/CapabilitiesSniff.php
  WordPress/Sniffs/WP/ClassNameCaseSniff.php
  WordPress/Sniffs/WP/DeprecatedClassesSniff.php
  WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php
  WordPress/Sniffs/WP/DeprecatedParameterValuesSniff.php
  WordPress/Sniffs/WP/DeprecatedParametersSniff.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.inc
  WordPress/Tests/WP/DeprecatedParameterValuesUnitTest.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
  WordPress/Tests/WP/DeprecatedParametersUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready

#2553 Update the `minimum_wp_version` to WP 6.5
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Tests/WP/DeprecatedClassesUnitTest.inc
  WordPress/Tests/WP/DeprecatedClassesUnitTest.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DeprecatedParametersUnitTest.inc
Labels: Type: Chores/Cleanup, Status: Review ready

#2556 CHANGELOG: fix indentation
  CHANGELOG.md
Labels: Status: Review ready, Type: Documentation

#2563 Use PHPCSUtils 1.1.0 features
  WordPress/Helpers/ListHelper.php
  WordPress/Sniffs/Files/FileNameSniff.php
  WordPress/Sniffs/PHP/YodaConditionsSniff.php
  WordPress/Sniffs/Security/EscapeOutputSniff.php
  WordPress/Sniffs/Utils/I18nTextDomainFixerSniff.php
  WordPress/Sniffs/WP/EnqueuedResourcesSniff.php
  WordPress/Tests/Security/EscapeOutputUnitTest.1.inc
  WordPress/Tests/Security/EscapeOutputUnitTest.php
Labels: Type: Chores/Cleanup, Type: Enhancement, Status: Review ready
