Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2025-06, with the labels that each got.

#2532 Composer: raise the minimum supported PHPCSUtils version to 1.1.0 + fix CI
  .github/CONTRIBUTING.md
  .github/workflows/unit-tests.yml
  WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.inc
  WordPress/Tests/NamingConventions/ValidVariableNameUnitTest.php
  composer.json
Labels: Type: Enhancement, Status: Review ready, Meta: Repo

#2534 Extra: add two new sniffs related to heredoc/nowdocs
  WordPress-Extra/ruleset.xml
Labels: Component: Extra, Type: Enhancement, Status: Review ready

#2533 Composer: bump PHP Parallel Lint
  composer.json
Labels: Type: Chores/Cleanup, Status: Review ready

#2512 Add tests for code handling STDIN for the sniffs FileName and I18nTextDomainFixer
  WordPress/Tests/Files/FileNameUnitTest.php
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready

#2539 GH Actions: add a basic spellcheck CI check + fix some typos
  .github/CONTRIBUTING.md
  .github/workflows/basic-qa.yml
  CHANGELOG.md
  README.md
  WordPress-Core/ruleset.xml
  WordPress/AbstractArrayAssignmentRestrictionsSniff.php
  WordPress/AbstractFunctionRestrictionsSniff.php
  WordPress/Docs/PHP/DontExtractStandard.xml
  WordPress/Helpers/MinimumWPVersionTrait.php
  WordPress/Helpers/WPDBTrait.php
  WordPress/Sniffs/Arrays/ArrayDeclarationSpacingSniff.php
  WordPress/Sniffs/CodeAnalysis/AssignmentInTernaryConditionSniff.php
  WordPress/Sniffs/DB/PreparedSQLPlaceholdersSniff.php
  WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php
  WordPress/Sniffs/NamingConventions/ValidFunctionNameSniff.php
  WordPress/Sniffs/PHP/NoSilencedErrorsSniff.php
  WordPress/Sniffs/WhiteSpace/CastStructureSpacingSniff.php
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.5.inc
  WordPress/Tests/Utils/I18nTextDomainFixerUnitTest.6.inc
  _typos.toml
Labels: Type: Chores/Cleanup, Type: Documentation
