Repository WordPress/WordPress-Coding-Standards, pull requests merged in 2025-09, with the labels that each got.

#2578 DB/RestrictedClasses: remove redundant call to `parent::setUpPrerequisites()`
  WordPress/Tests/DB/RestrictedClassesUnitTest.php
Labels: Type: Chores/Cleanup, Status: Review ready, Component: Core

#2600 Release checklist: add new bullet about checking all PRs are milestoned
  .github/release-checklist.md
Labels: Status: Review ready, Type: Documentation

#2601 Changelog: add WPCS maintainers to the list of GitHub profile links
  CHANGELOG.md
Labels: Type: Chores/Cleanup, Status: Review ready

#2604 WP/AlternativeFunctions: fix typo in code comment
  WordPress/Sniffs/WP/AlternativeFunctionsSniff.php
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review ready

#2609 README: make the call for funding stand out a bit more
  README.md
Labels: Status: Review ready, Type: Documentation

#2610 CONTRIBUTING: update the example test output
  .github/CONTRIBUTING.md
Labels: Status: Review ready, Type: Documentation

#2580 WP/GlobalVariablesOverride: more tests covering unresolvable `$GLOBALS` keys
  WordPress/Tests/WP/GlobalVariablesOverrideUnitTest.1.inc
Labels: Component: Extra, Type: Chores/Cleanup, Status: Review ready

#2613 DB/DirectDatabaseQuery: make cache function name matching case-insensitive
  WordPress/Sniffs/DB/DirectDatabaseQuerySniff.php
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.1.inc
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.2.inc
  WordPress/Tests/DB/DirectDatabaseQueryUnitTest.php
Labels: Type: Bug, Status: Review ready

#2471 Documentation: Update PHPCompatibilityWP version recommendation to 7.2
  README.md
Labels: Status: Review ready, Type: Documentation

#2581 AbstractFunctionRestrictions sniffs: add tests for namespaced names
  WordPress/Tests/DB/RestrictedFunctionsUnitTest.inc
  WordPress/Tests/DB/RestrictedFunctionsUnitTest.php
  WordPress/Tests/DateTime/RestrictedFunctionsUnitTest.inc
  WordPress/Tests/DateTime/RestrictedFunctionsUnitTest.php
  WordPress/Tests/PHP/DevelopmentFunctionsUnitTest.inc
  WordPress/Tests/PHP/DevelopmentFunctionsUnitTest.php
  WordPress/Tests/PHP/DiscouragedPHPFunctionsUnitTest.inc
  WordPress/Tests/PHP/DiscouragedPHPFunctionsUnitTest.php
  WordPress/Tests/PHP/DontExtractUnitTest.inc
  WordPress/Tests/PHP/DontExtractUnitTest.php
  WordPress/Tests/PHP/POSIXFunctionsUnitTest.inc
  WordPress/Tests/PHP/POSIXFunctionsUnitTest.php
  WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.inc
  WordPress/Tests/PHP/RestrictedPHPFunctionsUnitTest.php
  WordPress/Tests/Security/SafeRedirectUnitTest.inc
  WordPress/Tests/Security/SafeRedirectUnitTest.php
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.1.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.2.inc
  WordPress/Tests/WP/DeprecatedFunctionsUnitTest.php
  WordPress/Tests/WP/DiscouragedFunctionsUnitTest.inc
Labels: Type: Chores/Cleanup, Status: Review ready

#2621 GH Actions: "pin" all action runners
  .github/dependabot.yml
  .github/workflows/basic-qa.yml
  .github/workflows/manage-labels.yml
  .github/workflows/quicktest.yml
  .github/workflows/unit-tests.yml
Labels: Type: Chores/Cleanup, Status: Review ready
